[package]
name = "frontend"
description = "The frontend dashboard for Patr"

version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
leptos = { version = "0.4", features = ["tracing", "csr"] }
leptos-use = { version = "0.6", features = ["storage"] }
leptos_declarative = "0.3"
leptos_router = { version = "0.4", features = ["csr"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-logger = "0.2"
