[workspace]
members              = ["api", "cli", "cloudflare-ingress", "frontend/common", "frontend/managed", "frontend/self-hosted", "macros", "models", "runners/common", "runners/docker", "runners/kubernetes"]
package.authors      = ["Rakshith Ravi <rakshith.ravi@patr.cloud>"]
package.description  = "Patr API and all it's dependencies"
package.edition      = "2024"
package.rust-version = "1.85"
package.version      = "0.18.0"
resolver             = "3"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code  = "forbid"

[workspace.lints.clippy]
all                           = "warn"
cast_possible_truncation      = "warn"
cast_possible_wrap            = "warn"
cast_sign_loss                = "warn"
missing_docs_in_private_items = "warn"

[workspace.dependencies]
argon2                   = { default-features = false, version = "0.5" }
axum                     = { default-features = false, version = "0.8" }
axum-extra               = { default-features = false, version = "0.10" }
axum-typed-websockets    = { default-features = false, git = "https://github.com/morenol/axum-typed-websockets.git", branch = "patch-1" }
base32                   = { default-features = false, version = "0.5" }
base64                   = { default-features = false, version = "0.22" }
bollard                  = { default-features = false, version = "0.18" }
build-print              = { default-features = false, version = "1" }
clap                     = { default-features = false, version = "4" }
cloudflare               = { default-features = false, version = "0.14" }
codee                    = { default-features = false, version = "0.3" }
comfy-table              = { default-features = false, version = "7" }
common                   = { default-features = false, path = "runners/common" }
config                   = { default-features = false, version = "0.15" }
console_error_panic_hook = { default-features = false, version = "0.1" }
convert_case             = { default-features = false, version = "0.8" }
cookie                   = { default-features = false, version = "0.18" }
dashmap                  = { default-features = false, version = "6" }
dirs                     = { default-features = false, version = "6" }
either                   = { default-features = false, version = "1" }
flate2                   = { default-features = false, version = "1" }
frontend                 = { default-features = false, path = "frontend/common" }
fslock                   = { default-features = false, version = "0.2" }
futures                  = { default-features = false, version = "0.3" }
getrandom_02             = { default-features = false, package = "getrandom", version = "0.2" }
getrandom_03             = { default-features = false, package = "getrandom", version = "0.3" }
headers                  = { default-features = false, version = "0.4" }
hex                      = { default-features = false, version = "0.4" }
http                     = { default-features = false, version = "1" }
httparse                 = { default-features = false, version = "1" }
inquire                  = { default-features = false, version = "0.7" }
ipinfo                   = { default-features = false, version = "3" }
ipnetwork                = { default-features = false, version = "0.20" }
jsonwebtoken             = { default-features = false, version = "9" }
k8s-openapi              = { default-features = false, version = "0.25" }
kube                     = { default-features = false, version = "1" }
leptos                   = { default-features = false, version = "0.8" }
leptos-use               = { default-features = false, version = "0.16" }
leptos_axum              = { default-features = false, version = "0.8" }
leptos_meta              = { default-features = false, version = "0.8" }
leptos_router            = { default-features = false, version = "0.8" }
log                      = { default-features = false, version = "0.4" }
macros                   = { default-features = false, path = "macros" }
matchit                  = { default-features = false, version = "0.8" }
models                   = { default-features = false, path = "models" }
monostate                = { default-features = false, version = "0.1" }
nix                      = { default-features = false, version = "0.30" }
oci-spec                 = { default-features = false, version = "0.8" }
open                     = { default-features = false, version = "5" }
opentelemetry            = { default-features = false, version = "0.30" }
opentelemetry-otlp       = { default-features = false, version = "0.30" }
opentelemetry_sdk        = { default-features = false, version = "0.30" }
preprocess               = { default-features = false, version = "0.5" }
proc-macro2              = { default-features = false, version = "1" }
quote                    = { default-features = false, version = "1" }
rand                     = { default-features = false, version = "0.8" }
regex                    = { default-features = false, version = "1" }
reqwest                  = { default-features = false, version = "0.12" }
rust-embed               = { default-features = false, version = "8" }
rust-s3                  = { default-features = false, version = "0.36.0-beta" }
rustis                   = { default-features = false, version = "0.16" }
schemars                 = { default-features = false, version = "1" }
semver                   = { default-features = false, version = "1" }
serde                    = { default-features = false, version = "1" }
serde_json               = { default-features = false, version = "1" }
serde_test               = { default-features = false, version = "1" }
serde_urlencoded         = { default-features = false, version = "0.7" }
sha2                     = { default-features = false, version = "0.10" }
sqlx                     = { default-features = false, version = "0.8" }
strum                    = { default-features = false, version = "0.27" }
syn                      = { default-features = false, version = "2" }
tar                      = { default-features = false, version = "0.4" }
tempfile                 = { default-features = false, version = "3" }
thiserror                = { default-features = false, version = "2" }
time                     = { default-features = false, version = "0.3" }
tokio                    = { default-features = false, version = "1" }
tokio-stream             = { default-features = false, version = "0.1" }
tokio-tungstenite        = { default-features = false, version = "0.27" }
tokio-util               = { default-features = false, version = "0.7" }
totp-rs                  = { default-features = false, version = "5" }
tower                    = { default-features = false, version = "0.5" }
tower-http               = { default-features = false, version = "0.6" }
tracing                  = { default-features = false, version = "0.1" }
tracing-log              = { default-features = false, version = "0.2" }
tracing-opentelemetry    = { default-features = false, version = "0.31" }
tracing-subscriber       = { default-features = false, version = "0.3" }
typed-builder            = { default-features = false, version = "0.21" }
url                      = { default-features = false, version = "2" }
uuid                     = { default-features = false, version = "1" }
wasm-bindgen             = { default-features = false, version = "0.2" }
wasm-logger              = { default-features = false, version = "0.2" }
web-sys                  = { default-features = false, version = "0.3" }
woothee                  = { default-features = false, version = "0.13" }
worker                   = { default-features = false, version = "0.6" }

[workspace.dev-dependencies]
k8s-openapi = { features = ["latest"] }
models      = { features = ["default"] }

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 0

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
panic         = "abort"

[profile.frontend]
inherits  = "release"
opt-level = 's'
strip     = true

[[workspace.metadata.leptos]]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
bin-package = "api"
lib-package = "managed-frontend"
name        = "dashboard"
output-name = "dashboard"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/dashboard"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
site-pkg-dir        = "pkg"
style-file          = "assets/frontend/styles/index.scss"
tailwind-input-file = "assets/frontend/styles/global.css"
# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
assets-dir = "assets/frontend/public"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# The port to use for the live reload server
reload-port = 8080

[[workspace.metadata.leptos]]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
bin-package = "docker"
lib-package = "self-hosted-frontend"
name        = "docker"
output-name = "dashboard"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/docker-runner"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
site-pkg-dir        = "pkg"
style-file          = "assets/frontend/styles/index.scss"
tailwind-input-file = "assets/frontend/styles/global.css"
# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
assets-dir = "assets/frontend/public"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# The profile to use for the lib target when compiling for release
lib-profile-release = "frontend"
# The port to use for the live reload server
reload-port = 8080
