[workspace]
members = ["api", "macros", "api-models"]

[workspace.package]
version = "0.14.0"
rust-version = "1.65"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"

[patch."https://github.com/vicara-hq/cloudflare-rs"]
cloudflare = { git = "https://github.com/kavin-kr/cloudflare-rs", branch = "feature/custom_hostname" }
