[workspace]
members = [
  "api",
  "macros",
  "api-models"
]

[workspace.package]
version = "0.11.0"
rust-version = "1.64"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
