[workspace]
members = [
   "api",
    "macros",
    "models",
    "controller",
    "cloudflare-ingress",
    "frontend",
    "cli",
]
package.authors = ["Rakshith Ravi <rakshith.ravi@patr.cloud>"]
package.description = "Patr API and all it's dependencies"
package.edition = "2021"
package.rust-version = "1.71"
package.version = "0.18.0"
resolver = "2"

[workspace.dependencies]
macros = { path = "macros" }
models = { path = "models", default-features = false }
tokio = { version = "1", features = ["full"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"

[profile.frontend]
inherits = "release"
opt-level = 'z'
strip = true
