[workspace]
members = ["api", "macros", "api-models", "k8s_agent"]

[workspace.package]
version = "0.16.1"
rust-version = "1.69"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
