[workspace]
members              = ["api", "cli", "ingress", "macros", "models", "runners/common", "runners/docker", "runners/kubernetes"]
package.authors      = ["Rakshith Ravi <rakshith.ravi@patr.cloud>"]
package.description  = "Patr API and all it's dependencies"
package.edition      = "2024"
package.rust-version = "1.94"
package.version      = "0.18.0"
resolver             = "3"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code  = "forbid"

[workspace.lints.clippy]
all                           = "warn"
cast_possible_truncation      = "warn"
cast_possible_wrap            = "warn"
cast_sign_loss                = "warn"
missing_docs_in_private_items = "warn"

[workspace.dependencies]
anyhow                         = { default-features = false, version = "1" }
apalis                         = { default-features = false, version = "1.0.0-rc.1" }
apalis-cron                    = { default-features = false, version = "1.0.0-rc.1" }
apalis-postgres                = { default-features = false, version = "1.0.0-rc.3" }
argon2                         = { default-features = false, version = "0.6.0-rc.7" }
askama                         = { default-features = false, version = "0.16" }
aws-config                     = { default-features = false, version = "1" }
aws-credential-types           = { default-features = false, version = "1" }
aws-sdk-s3                     = { default-features = false, version = "1" }
axum                           = { default-features = false, version = "0.8" }
axum-extra                     = { default-features = false, version = "0.12" }
axum-test                      = { default-features = false, version = "20" }
axum-typed-websockets          = { default-features = false, git = "https://github.com/cachix/axum-typed-websockets" }
base32                         = { default-features = false, version = "0.5" }
base64                         = { default-features = false, version = "0.22" }
bollard                        = { default-features = false, version = "0.21" }
build-print                    = { default-features = false, version = "1" }
clap                           = { default-features = false, version = "4" }
cloudflare                     = { default-features = false, git = "https://github.com/rakshith-ravi/cloudflare-rs", branch = "patr-must-haves" }
comfy-table                    = { default-features = false, version = "7" }
common                         = { default-features = false, path = "runners/common" }
config                         = { default-features = false, version = "0.15" }
console-subscriber             = { default-features = false, version = "0.5" }
console_error_panic_hook       = { default-features = false, version = "0.1" }
convert_case                   = { default-features = false, version = "0.11" }
cron                           = { default-features = false, version = "0.16" }
crossterm                      = { default-features = false, version = "0.29" }
dashmap                        = { default-features = false, version = "6" }
derive_more                    = { default-features = false, version = "2" }
dirs                           = { default-features = false, version = "6" }
docker                         = { default-features = false, path = "runners/docker" }
either                         = { default-features = false, version = "1" }
flate2                         = { default-features = false, version = "1" }
fslock                         = { default-features = false, version = "0.2" }
futures                        = { default-features = false, version = "0.3" }
getrandom                      = { default-features = false, version = "0.3" }
headers                        = { default-features = false, version = "0.4" }
hex                            = { default-features = false, version = "0.4" }
hickory-resolver               = { default-features = false, version = "0.26" }
http                           = { default-features = false, version = "1" }
http-body                      = { default-features = false, version = "1" }
httparse                       = { default-features = false, version = "1" }
hyper                          = { default-features = false, version = "1" }
if-addrs                       = { default-features = false, version = "0.15" }
inquire                        = { default-features = false, version = "0.9" }
inventory                      = { default-features = false, version = "0.3" }
ipinfo                         = { default-features = false, version = "3" }
ipnetwork                      = { default-features = false, version = "0.20" }
jsonwebtoken                   = { default-features = false, version = "10" }
k8s-openapi                    = { default-features = false, version = "0.27" }
kube                           = { default-features = false, version = "3" }
lettre                         = { default-features = false, version = "0.11" }
macros                         = { default-features = false, path = "macros" }
mime_guess                     = { default-features = false, version = "2" }
models                         = { default-features = false, path = "models" }
monostate                      = { default-features = false, version = "1" }
mrml                           = { default-features = false, version = "6" }
nix                            = { default-features = false, version = "0.31" }
oci-spec                       = { default-features = false, version = "0.9" }
open                           = { default-features = false, version = "5" }
opentelemetry                  = { default-features = false, version = "0.31" }
opentelemetry-appender-tracing = { default-features = false, version = "0.31" }
opentelemetry-otlp             = { default-features = false, version = "0.31" }
opentelemetry-proto            = { default-features = false, version = "0.31" }
opentelemetry_sdk              = { default-features = false, version = "0.31" }
pin-project                    = { default-features = false, version = "1" }
preprocess                     = { default-features = false, version = "0.5" }
proc-macro2                    = { default-features = false, version = "1" }
prost                          = { default-features = false, version = "0.14" }
prost-types                    = { default-features = false, version = "0.14" }
psl                            = { default-features = false, version = "2" }
quote                          = { default-features = false, version = "1" }
ractor                         = { default-features = false, version = "0.15" }
ractor_actors                  = { default-features = false, version = "0.5" }
rand                           = { default-features = false, version = "0.10" }
regex                          = { default-features = false, version = "1" }
reqwest                        = { default-features = false, version = "0.13" }
rust-embed                     = { default-features = false, version = "8" }
rust-s3                        = { default-features = false, version = "0.37" }
rustis                         = { default-features = false, version = "0.19" }
rustls                         = { default-features = false, version = "0.23" }
schemars                       = { default-features = false, version = "1" }
self-replace                   = { default-features = false, version = "1" }
semver                         = { default-features = false, version = "1" }
serde                          = { default-features = false, version = "1" }
serde_json                     = { default-features = false, version = "1" }
serde_path_to_error            = { default-features = false, version = "0.1" }
serde_qs                       = { default-features = false, version = "1" }
serde_test                     = { default-features = false, version = "1" }
serde_yaml2                    = { default-features = false, version = "0.1" }
sha2                           = { default-features = false, version = "0.11" }
snap                           = { default-features = false, version = "1" }
sqlx                           = { default-features = false, version = "0.8" }
strum                          = { default-features = false, version = "0.28" }
syn                            = { default-features = false, version = "2" }
sync_wrapper                   = { default-features = false, version = "1" }
tar                            = { default-features = false, version = "0.4" }
tempfile                       = { default-features = false, version = "3" }
thiserror                      = { default-features = false, version = "2" }
time                           = { default-features = false, version = "0.3" }
tokio                          = { default-features = false, version = "1" }
tokio-stream                   = { default-features = false, version = "0.1" }
tokio-tungstenite              = { default-features = false, version = "0.29" }
tokio-util                     = { default-features = false, version = "0.7" }
totp-rs                        = { default-features = false, version = "5" }
tower                          = { default-features = false, version = "0.5" }
tower-http                     = { default-features = false, version = "0.6" }
tracing                        = { default-features = false, version = "0.1" }
tracing-log                    = { default-features = false, version = "0.2" }
tracing-opentelemetry          = { default-features = false, version = "0.32" }
tracing-subscriber             = { default-features = false, version = "0.3" }
ts-rs                          = { default-features = false, version = "12" }
typed-builder                  = { default-features = false, version = "0.23" }
url                            = { default-features = false, version = "2" }
uuid                           = { default-features = false, version = "1" }
uzers                          = { default-features = false, version = "0.12" }
wiremock                       = { default-features = false, version = "0.6" }
woothee                        = { default-features = false, version = "0.13" }
worker                         = { default-features = false, version = "0.8" }
zip                            = { default-features = false, version = "8" }

[workspace.dev-dependencies]
k8s-openapi = { features = ["latest"] }
models      = { features = ["default"] }

[profile.dev]
debug     = true
lto       = false
opt-level = 0

[profile.dev.package."*"]
debug     = true
opt-level = 0

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
panic         = "abort"
