//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::CiGitProviderType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ci_git_provider")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub workspace_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub domain_name: String,
	pub git_provider_type: CiGitProviderType,
	#[sea_orm(column_type = "Text", nullable)]
	pub login_name: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub password: Option<String>,
	pub is_deleted: bool,
	pub is_syncing: bool,
	pub last_synced: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::ci_repos::Entity")]
	CiRepos,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::ci_repos::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CiRepos.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
