//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::CiBuildStepStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ci_steps")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub repo_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub build_num: i64,
	#[sea_orm(primary_key, auto_increment = false)]
	pub step_id: i32,
	#[sea_orm(column_type = "Text")]
	pub step_name: String,
	#[sea_orm(column_type = "Text")]
	pub base_image: String,
	#[sea_orm(column_type = "Text")]
	pub commands: String,
	pub status: CiBuildStepStatus,
	pub started: Option<DateTimeWithTimeZone>,
	pub finished: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::ci_builds::Entity",
		from = "Column::RepoId",
		to = "super::ci_builds::Column::RepoId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	CiBuilds,
}

impl Related<super::ci_builds::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CiBuilds.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
