//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "deployment_deploy_history")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub deployment_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub image_digest: String,
	pub repository_id: Uuid,
	pub created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "Column::DeploymentId",
		to = "super::deployment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
	#[sea_orm(
		belongs_to = "super::docker_registry_repository::Entity",
		from = "Column::RepositoryId",
		to = "super::docker_registry_repository::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	DockerRegistryRepository,
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl Related<super::docker_registry_repository::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DockerRegistryRepository.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
