//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "domain_tld")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub tld: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::domain::Entity")]
	Domain,
}

impl Related<super::domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Domain.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
