//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
	ManagedDatabaseEngine,
	ManagedDatabaseStatus,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "managed_database")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(column_type = "custom(\"citext\")")]
	pub name: String,
	pub workspace_id: Uuid,
	pub region: Uuid,
	pub engine: ManagedDatabaseEngine,
	pub database_plan_id: Uuid,
	pub status: ManagedDatabaseStatus,
	#[sea_orm(column_type = "Text")]
	pub username: String,
	pub deleted: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::managed_database_plan::Entity",
		from = "Column::DatabasePlanId",
		to = "super::managed_database_plan::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ManagedDatabasePlan,
	#[sea_orm(
		belongs_to = "super::region::Entity",
		from = "Column::Region",
		to = "super::region::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Region,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "Column::Id",
		to = "super::resource::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::managed_database_plan::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedDatabasePlan.def()
	}
}

impl Related<super::region::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Region.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
