//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::LegacyManagedDatabasePlan;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "managed_database_payment_history")]
pub struct Model {
	pub workspace_id: Uuid,
	pub database_id: Uuid,
	pub db_plan_id: Option<Uuid>,
	pub legacy_db_plan: Option<LegacyManagedDatabasePlan>,
	pub start_time: DateTimeWithTimeZone,
	pub deletion_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::managed_database_plan::Entity",
		from = "Column::DbPlanId",
		to = "super::managed_database_plan::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ManagedDatabasePlan,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::managed_database_plan::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedDatabasePlan.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
