//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{PermissionType, TokenPermissionType};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_api_token_resource_permissions_type")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub workspace_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub permission_id: Uuid,
	pub resource_permission_type: PermissionType,
	pub token_permission_type: TokenPermissionType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::permission::Entity",
		from = "Column::PermissionId",
		to = "super::permission::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Permission,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_exclude::Entity")]
	UserApiTokenResourcePermissionsExclude,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_include::Entity")]
	UserApiTokenResourcePermissionsInclude,
	#[sea_orm(
		belongs_to = "super::user_api_token_workspace_permission_type::Entity",
		from = "Column::TokenId",
		to = "super::user_api_token_workspace_permission_type::Column::TokenPermissionType",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserApiTokenWorkspacePermissionType,
}

impl Related<super::permission::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Permission.def()
	}
}

impl Related<super::user_api_token_resource_permissions_exclude::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsExclude.def()
	}
}

impl Related<super::user_api_token_resource_permissions_include::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsInclude.def()
	}
}

impl Related<super::user_api_token_workspace_permission_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenWorkspacePermissionType.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
