//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_unverified_phone_number")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub country_code: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub phone_number: String,
	pub user_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub verification_token_hash: String,
	pub verification_token_expiry: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::phone_number_country_code::Entity",
		from = "Column::CountryCode",
		to = "super::phone_number_country_code::Column::CountryCode",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	PhoneNumberCountryCode,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::phone_number_country_code::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PhoneNumberCountryCode.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
