//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::TokenPermissionType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_api_token_workspace_permission_type")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub workspace_id: Uuid,
	pub token_permission_type: TokenPermissionType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user_api_token::Entity",
		from = "Column::TokenId",
		to = "super::user_api_token::Column::TokenId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserApiToken,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_type::Entity")]
	UserApiTokenResourcePermissionsType,
	#[sea_orm(has_many = "super::user_api_token_workspace_super_admin::Entity")]
	UserApiTokenWorkspaceSuperAdmin,
}

impl Related<super::user_api_token::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiToken.def()
	}
}

impl Related<super::user_api_token_resource_permissions_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsType.def()
	}
}

impl Related<super::user_api_token_workspace_super_admin::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenWorkspaceSuperAdmin.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
