//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "volume_payment_history")]
pub struct Model {
	pub workspace_id: Uuid,
	pub volume_id: Uuid,
	pub storage: i64,
	pub number_of_volumes: i32,
	pub start_time: DateTimeWithTimeZone,
	pub stop_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
