//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::AuditLogType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "audit_log")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub timestamp: TimeDateTimeWithTimeZone,
	#[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text")]
	pub ip: String,
	#[sea_orm(ignore, column_type = "custom(\"geometry\")", select_as = "text")]
	pub location: String,
	#[sea_orm(column_type = "Text")]
	pub user_agent: String,
	#[sea_orm(column_type = "Text")]
	pub country: String,
	#[sea_orm(column_type = "Text")]
	pub region: String,
	#[sea_orm(column_type = "Text")]
	pub city: String,
	#[sea_orm(column_type = "Text")]
	pub timezone: String,
	pub login_id: Uuid,
	pub action: AuditLogType,
	pub workspace_id: Uuid,
	pub resource_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "Column::ResourceId",
		to = "super::resource::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::user_login::Entity",
		from = "Column::LoginId",
		to = "super::user_login::Column::LoginId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserLogin,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::user_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserLogin.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
