//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_registry_manifest_reference")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub digest: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub referenced_digest: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::container_registry_manifest::Entity",
		from = "Column::Digest",
		to = "super::container_registry_manifest::Column::Digest",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryManifest2,
	#[sea_orm(
		belongs_to = "super::container_registry_manifest::Entity",
		from = "Column::ReferencedDigest",
		to = "super::container_registry_manifest::Column::Digest",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryManifest1,
}

impl ActiveModelBehavior for ActiveModel {}
