//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_registry_manifest")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub digest: String,
	#[sea_orm(column_type = "Text")]
	pub content_type: String,
	pub size: i64,
	#[sea_orm(column_type = "Text")]
	pub config_blob_digest: String,
	#[sea_orm(column_type = "Text")]
	pub platform: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::container_registry_blob::Entity",
		from = "Column::ConfigBlobDigest",
		to = "super::container_registry_blob::Column::Digest",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryBlob,
	#[sea_orm(has_many = "super::container_registry_manifest_blob::Entity")]
	ContainerRegistryManifestBlob,
	#[sea_orm(has_many = "super::container_registry_repository_manifest::Entity")]
	ContainerRegistryRepositoryManifest,
}

impl Related<super::container_registry_manifest_blob::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryManifestBlob.def()
	}
}

impl Related<super::container_registry_repository_manifest::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryRepositoryManifest.def()
	}
}

impl Related<super::container_registry_blob::Entity> for Entity {
	fn to() -> RelationDef {
		super::container_registry_manifest_blob::Relation::ContainerRegistryBlob.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::container_registry_manifest_blob::Relation::ContainerRegistryManifest
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
