//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_registry_blob")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub digest: String,
	pub size: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::container_registry_manifest::Entity")]
	ContainerRegistryManifest,
	#[sea_orm(has_many = "super::container_registry_manifest_blob::Entity")]
	ContainerRegistryManifestBlob,
}

impl Related<super::container_registry_manifest_blob::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryManifestBlob.def()
	}
}

impl Related<super::container_registry_manifest::Entity> for Entity {
	fn to() -> RelationDef {
		super::container_registry_manifest_blob::Relation::ContainerRegistryManifest.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::container_registry_manifest_blob::Relation::ContainerRegistryBlob
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
