//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_registry_manifest_blob")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub manifest_digest: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub blob_digest: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::container_registry_blob::Entity",
		from = "Column::BlobDigest",
		to = "super::container_registry_blob::Column::Digest",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryBlob,
	#[sea_orm(
		belongs_to = "super::container_registry_manifest::Entity",
		from = "Column::ManifestDigest",
		to = "super::container_registry_manifest::Column::Digest",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryManifest,
}

impl Related<super::container_registry_blob::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryBlob.def()
	}
}

impl Related<super::container_registry_manifest::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryManifest.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
