//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_registry_repository")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "container_registry_repository_uq_id_workspace_id"
	)]
	pub id: Uuid,
	#[sea_orm(unique_key = "container_registry_repository_uq_name_workspace_id")]
	pub workspace_id: Uuid,
	#[sea_orm(
		column_type = "Text",
		unique_key = "container_registry_repository_uq_name_workspace_id"
	)]
	pub name: String,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::container_registry_repository_manifest::Entity")]
	ContainerRegistryRepositoryManifest,
	#[sea_orm(has_many = "super::container_registry_repository_tag::Entity")]
	ContainerRegistryRepositoryTag,
	#[sea_orm(has_many = "super::deployment::Entity")]
	Deployment,
	#[sea_orm(has_many = "super::deployment_deploy_history::Entity")]
	DeploymentDeployHistory,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::container_registry_repository_tag::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryRepositoryTag.def()
	}
}

impl Related<super::deployment_deploy_history::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DeploymentDeployHistory.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl Related<super::container_registry_repository_manifest::Entity> for Entity {
	fn to() -> RelationDef {
		super::container_registry_repository_tag::Relation::ContainerRegistryRepositoryManifest
			.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::container_registry_repository_tag::Relation::ContainerRegistryRepository
				.def()
				.rev(),
		)
	}
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		super::deployment_deploy_history::Relation::Deployment.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::deployment_deploy_history::Relation::ContainerRegistryRepository
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
