//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_config_mounts")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub path: String,
	#[sea_orm(column_type = "VarBinary(StringLen::None)")]
	pub file: Vec<u8>,
	#[sea_orm(primary_key, auto_increment = false)]
	pub deployment_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "Column::DeploymentId",
		to = "super::deployment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
