//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_deploy_history")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub deployment_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub image_digest: String,
	pub repository_id: Uuid,
	pub created: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::container_registry_repository::Entity",
		from = "Column::RepositoryId",
		to = "super::container_registry_repository::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ContainerRegistryRepository,
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "Column::DeploymentId",
		to = "super::deployment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
}

impl Related<super::container_registry_repository::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryRepository.def()
	}
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
