//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::ExposedPortType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_exposed_port")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "deployment_exposed_port_uq_deployment_id_port_port_type"
	)]
	pub deployment_id: Uuid,
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "deployment_exposed_port_uq_deployment_id_port_port_type"
	)]
	pub port: i32,
	#[sea_orm(unique_key = "deployment_exposed_port_uq_deployment_id_port_port_type")]
	pub port_type: ExposedPortType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "Column::DeploymentId",
		to = "super::deployment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
	#[sea_orm(has_many = "super::managed_url::Entity")]
	ManagedUrl,
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl Related<super::managed_url::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrl.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
