//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_volume_mount")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub deployment_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub volume_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub volume_mount_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "Column::DeploymentId",
		to = "super::deployment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
	#[sea_orm(
		belongs_to = "super::deployment_volume::Entity",
		from = "Column::VolumeId",
		to = "super::deployment_volume::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	DeploymentVolume,
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl Related<super::deployment_volume::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DeploymentVolume.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
