//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_volume")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	pub volume_size: i64,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::deployment_volume_mount::Entity")]
	DeploymentVolumeMount,
}

impl Related<super::deployment_volume_mount::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DeploymentVolumeMount.def()
	}
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		super::deployment_volume_mount::Relation::Deployment.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::deployment_volume_mount::Relation::DeploymentVolume
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
