//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "managed_url_custom_hostname")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub sub_domain: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub domain_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub cloudflare_custom_hostname_id: String,
	pub is_active: bool,
	pub last_verified: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::managed_url::Entity")]
	ManagedUrl,
	#[sea_orm(
		belongs_to = "super::workspace_domain::Entity",
		from = "Column::DomainId",
		to = "super::workspace_domain::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	WorkspaceDomain,
}

impl Related<super::managed_url::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrl.def()
	}
}

impl Related<super::workspace_domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceDomain.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
