//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{ManagedDatabaseEngine, ManagedDatabaseStatus};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "managed_database")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(
		ignore,
		column_type = "custom(\"citext\")",
		select_as = "text",
		unique_key = "managed_database_uq_workspace_id_name"
	)]
	pub name: String,
	#[sea_orm(unique_key = "managed_database_uq_workspace_id_name")]
	pub workspace_id: Uuid,
	pub runner: Uuid,
	pub engine: ManagedDatabaseEngine,
	pub database_plan_id: Uuid,
	pub status: ManagedDatabaseStatus,
	#[sea_orm(column_type = "Text")]
	pub username: String,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::managed_database_plan::Entity",
		from = "Column::DatabasePlanId",
		to = "super::managed_database_plan::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ManagedDatabasePlan,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::Id, Column::WorkspaceId, Column::Deleted)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId, super::resource::Column::Deleted)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::runner::Entity",
		from = "Column::Runner",
		to = "super::runner::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Runner,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::managed_database_plan::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedDatabasePlan.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::runner::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Runner.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
