//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::ManagedUrlType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "managed_url")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(
		column_type = "Text",
		unique_key = "managed_url_uq_sub_domain_domain_id_path"
	)]
	pub sub_domain: String,
	#[sea_orm(unique_key = "managed_url_uq_sub_domain_domain_id_path")]
	pub domain_id: Uuid,
	#[sea_orm(
		column_type = "Text",
		unique_key = "managed_url_uq_sub_domain_domain_id_path"
	)]
	pub path: String,
	pub url_type: ManagedUrlType,
	pub deployment_id: Option<Uuid>,
	pub port: Option<i32>,
	pub static_site_id: Option<Uuid>,
	#[sea_orm(column_type = "Text", nullable)]
	pub url: Option<String>,
	pub workspace_id: Uuid,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
	pub permanent_redirect: Option<bool>,
	pub http_only: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::deployment::Entity",
		from = "(Column::DeploymentId, Column::WorkspaceId)",
		to = "(super::deployment::Column::Id, super::deployment::Column::WorkspaceId)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Deployment,
	#[sea_orm(
		belongs_to = "super::deployment_exposed_port::Entity",
		from = "(Column::DeploymentId, Column::Port)",
		to = "(super::deployment_exposed_port::Column::DeploymentId, super::deployment_exposed_port::Column::Port)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	DeploymentExposedPort,
	#[sea_orm(
		belongs_to = "super::managed_url_custom_hostname::Entity",
		from = "(Column::SubDomain, Column::DomainId)",
		to = "(super::managed_url_custom_hostname::Column::SubDomain, super::managed_url_custom_hostname::Column::DomainId)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ManagedUrlCustomHostname,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::Id, Column::WorkspaceId, Column::Deleted)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId, super::resource::Column::Deleted)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::static_site::Entity",
		from = "(Column::StaticSiteId, Column::WorkspaceId)",
		to = "(super::static_site::Column::Id, super::static_site::Column::WorkspaceId)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	StaticSite,
	#[sea_orm(
		belongs_to = "super::workspace_domain::Entity",
		from = "Column::DomainId",
		to = "super::workspace_domain::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	WorkspaceDomain,
}

impl Related<super::deployment_exposed_port::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DeploymentExposedPort.def()
	}
}

impl Related<super::managed_url_custom_hostname::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrlCustomHostname.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::static_site::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::StaticSite.def()
	}
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		super::deployment_exposed_port::Relation::Deployment.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::deployment_exposed_port::Relation::ManagedUrl
				.def()
				.rev(),
		)
	}
}

impl Related<super::workspace_domain::Entity> for Entity {
	fn to() -> RelationDef {
		super::managed_url_custom_hostname::Relation::WorkspaceDomain.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::managed_url_custom_hostname::Relation::ManagedUrl
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
