//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "permission")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique)]
	pub name: String,
	pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::role_resource_permissions_type::Entity")]
	RoleResourcePermissionsType,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_type::Entity")]
	UserApiTokenResourcePermissionsType,
}

impl Related<super::role_resource_permissions_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleResourcePermissionsType.def()
	}
}

impl Related<super::user_api_token_resource_permissions_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsType.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
