//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "resource")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "resource_uq_id_owner_id_deleted"
	)]
	pub id: Uuid,
	pub resource_type_id: Uuid,
	#[sea_orm(unique_key = "resource_uq_id_owner_id_deleted")]
	pub owner_id: Uuid,
	pub created: TimeDateTimeWithTimeZone,
	#[sea_orm(unique_key = "resource_uq_id_owner_id_deleted")]
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::audit_log::Entity")]
	AuditLog,
	#[sea_orm(has_many = "super::deployment::Entity")]
	Deployment,
	#[sea_orm(has_many = "super::managed_database::Entity")]
	ManagedDatabase,
	#[sea_orm(has_many = "super::managed_url::Entity")]
	ManagedUrl,
	#[sea_orm(has_one = "super::patr_domain_dns_record::Entity")]
	PatrDomainDnsRecord,
	#[sea_orm(
		belongs_to = "super::resource_type::Entity",
		from = "Column::ResourceTypeId",
		to = "super::resource_type::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ResourceType,
	#[sea_orm(has_many = "super::role::Entity")]
	Role,
	#[sea_orm(has_many = "super::role_resource_permissions_exclude::Entity")]
	RoleResourcePermissionsExclude,
	#[sea_orm(has_many = "super::role_resource_permissions_include::Entity")]
	RoleResourcePermissionsInclude,
	#[sea_orm(has_many = "super::runner::Entity")]
	Runner,
	#[sea_orm(has_many = "super::secret::Entity")]
	Secret,
	#[sea_orm(has_many = "super::static_site::Entity")]
	StaticSite,
	#[sea_orm(has_one = "super::static_site_upload_history::Entity")]
	StaticSiteUploadHistory,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_exclude::Entity")]
	UserApiTokenResourcePermissionsExclude,
	#[sea_orm(has_many = "super::user_api_token_resource_permissions_include::Entity")]
	UserApiTokenResourcePermissionsInclude,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::OwnerId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
	#[sea_orm(has_many = "super::workspace_domain::Entity")]
	WorkspaceDomain,
}

impl Related<super::audit_log::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::AuditLog.def()
	}
}

impl Related<super::deployment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Deployment.def()
	}
}

impl Related<super::managed_database::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedDatabase.def()
	}
}

impl Related<super::managed_url::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrl.def()
	}
}

impl Related<super::patr_domain_dns_record::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PatrDomainDnsRecord.def()
	}
}

impl Related<super::resource_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ResourceType.def()
	}
}

impl Related<super::role::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Role.def()
	}
}

impl Related<super::role_resource_permissions_exclude::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleResourcePermissionsExclude.def()
	}
}

impl Related<super::role_resource_permissions_include::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleResourcePermissionsInclude.def()
	}
}

impl Related<super::runner::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Runner.def()
	}
}

impl Related<super::secret::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Secret.def()
	}
}

impl Related<super::static_site::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::StaticSite.def()
	}
}

impl Related<super::static_site_upload_history::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::StaticSiteUploadHistory.def()
	}
}

impl Related<super::user_api_token_resource_permissions_exclude::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsExclude.def()
	}
}

impl Related<super::user_api_token_resource_permissions_include::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsInclude.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl Related<super::workspace_domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceDomain.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
