//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "role")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique_key = "role_uq_name_owner_id")]
	pub name: String,
	pub description: String,
	#[sea_orm(unique_key = "role_uq_name_owner_id")]
	pub owner_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::Id, Column::OwnerId)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(has_many = "super::role_resource_permissions_type::Entity")]
	RoleResourcePermissionsType,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::OwnerId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
	#[sea_orm(has_many = "super::workspace_user::Entity")]
	WorkspaceUser,
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::role_resource_permissions_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleResourcePermissionsType.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl Related<super::workspace_user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceUser.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
