//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "audit_log_type")]
pub enum AuditLogType {
	#[sea_orm(string_value = "create")]
	Create,
	#[sea_orm(string_value = "update")]
	Update,
	#[sea_orm(string_value = "delete")]
	Delete,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "deployment_status")]
pub enum DeploymentStatus {
	#[sea_orm(string_value = "created")]
	Created,
	#[sea_orm(string_value = "pushed")]
	Pushed,
	#[sea_orm(string_value = "deploying")]
	Deploying,
	#[sea_orm(string_value = "running")]
	Running,
	#[sea_orm(string_value = "stopped")]
	Stopped,
	#[sea_orm(string_value = "errored")]
	Errored,
	#[sea_orm(string_value = "deleted")]
	Deleted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "dns_record_type")]
pub enum DnsRecordType {
	#[sea_orm(string_value = "A")]
	A,
	#[sea_orm(string_value = "MX")]
	Mx,
	#[sea_orm(string_value = "TXT")]
	Txt,
	#[sea_orm(string_value = "AAAA")]
	Aaaa,
	#[sea_orm(string_value = "CNAME")]
	Cname,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
	rs_type = "Enum",
	db_type = "Enum",
	enum_name = "domain_nameserver_type"
)]
pub enum DomainNameserverType {
	#[sea_orm(string_value = "internal")]
	Internal,
	#[sea_orm(string_value = "external")]
	External,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "exposed_port_type")]
pub enum ExposedPortType {
	#[sea_orm(string_value = "http")]
	Http,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
	rs_type = "Enum",
	db_type = "Enum",
	enum_name = "managed_database_engine"
)]
pub enum ManagedDatabaseEngine {
	#[sea_orm(string_value = "postgres")]
	Postgres,
	#[sea_orm(string_value = "mysql")]
	Mysql,
	#[sea_orm(string_value = "mongo")]
	Mongo,
	#[sea_orm(string_value = "redis")]
	Redis,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
	rs_type = "Enum",
	db_type = "Enum",
	enum_name = "managed_database_status"
)]
pub enum ManagedDatabaseStatus {
	#[sea_orm(string_value = "creating")]
	Creating,
	#[sea_orm(string_value = "running")]
	Running,
	#[sea_orm(string_value = "errored")]
	Errored,
	#[sea_orm(string_value = "deleted")]
	Deleted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "managed_url_type")]
pub enum ManagedUrlType {
	#[sea_orm(string_value = "proxy_to_deployment")]
	ProxyToDeployment,
	#[sea_orm(string_value = "proxy_to_static_site")]
	ProxyToStaticSite,
	#[sea_orm(string_value = "proxy_url")]
	ProxyUrl,
	#[sea_orm(string_value = "redirect")]
	Redirect,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "permission_type")]
pub enum PermissionType {
	#[sea_orm(string_value = "include")]
	Include,
	#[sea_orm(string_value = "exclude")]
	Exclude,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
	rs_type = "Enum",
	db_type = "Enum",
	enum_name = "social_login_provider"
)]
pub enum SocialLoginProvider {
	#[sea_orm(string_value = "github")]
	Github,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
	rs_type = "Enum",
	db_type = "Enum",
	enum_name = "token_permission_type"
)]
pub enum TokenPermissionType {
	#[sea_orm(string_value = "super_admin")]
	SuperAdmin,
	#[sea_orm(string_value = "member")]
	Member,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "user_login_type")]
pub enum UserLoginType {
	#[sea_orm(string_value = "api_token")]
	ApiToken,
	#[sea_orm(string_value = "web_login")]
	WebLogin,
}
