//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::DeploymentStatus;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "static_site")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "static_site_uq_id_workspace_id"
	)]
	pub id: Uuid,
	#[sea_orm(
		ignore,
		column_type = "custom(\"citext\")",
		select_as = "text",
		unique_key = "static_site_uq_name_workspace_id"
	)]
	pub name: String,
	pub status: DeploymentStatus,
	#[sea_orm(unique_key = "static_site_uq_name_workspace_id")]
	pub workspace_id: Uuid,
	pub current_live_upload: Option<Uuid>,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::managed_url::Entity")]
	ManagedUrl,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::Id, Column::WorkspaceId, Column::Deleted)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId, super::resource::Column::Deleted)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::static_site_upload_history::Entity",
		from = "(Column::Id, Column::CurrentLiveUpload)",
		to = "(super::static_site_upload_history::Column::StaticSiteId, super::static_site_upload_history::Column::UploadId)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	StaticSiteUploadHistory,
}

impl Related<super::managed_url::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrl.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::static_site_upload_history::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::StaticSiteUploadHistory.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
