//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::PermissionType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_api_token_resource_permissions_exclude")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub workspace_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub permission_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub resource_id: Uuid,
	pub resource_deleted: Option<TimeDateTimeWithTimeZone>,
	pub permission_type: PermissionType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::ResourceId, Column::WorkspaceId, Column::ResourceDeleted)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId, super::resource::Column::Deleted)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(
		belongs_to = "super::user_api_token_resource_permissions_type::Entity",
		from = "(Column::TokenId, Column::WorkspaceId, Column::PermissionId, Column::PermissionType)",
		to = "(super::user_api_token_resource_permissions_type::Column::TokenId, super::user_api_token_resource_permissions_type::Column::WorkspaceId, super::user_api_token_resource_permissions_type::Column::PermissionId, super::user_api_token_resource_permissions_type::Column::ResourcePermissionType)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserApiTokenResourcePermissionsType,
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::user_api_token_resource_permissions_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenResourcePermissionsType.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
