//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique)]
	pub username: String,
	#[sea_orm(column_type = "Text")]
	pub password: String,
	pub first_name: String,
	pub last_name: String,
	pub created: TimeDateTimeWithTimeZone,
	#[sea_orm(column_type = "Text", nullable, unique)]
	pub recovery_email: Option<String>,
	#[sea_orm(unique_key = "user_uq_recovery_phone_country_code_recovery_phone_number")]
	pub recovery_phone_country_code: Option<String>,
	#[sea_orm(unique_key = "user_uq_recovery_phone_country_code_recovery_phone_number")]
	pub recovery_phone_number: Option<String>,
	pub workspace_limit: i32,
	#[sea_orm(column_type = "Text", nullable)]
	pub password_reset_token: Option<String>,
	pub password_reset_token_expiry: Option<TimeDateTimeWithTimeZone>,
	pub password_reset_attempts: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub mfa_secret: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::static_site_upload_history::Entity")]
	StaticSiteUploadHistory,
	#[sea_orm(
		belongs_to = "super::user_email::Entity",
		from = "(Column::Id, Column::RecoveryEmail)",
		to = "(super::user_email::Column::UserId, super::user_email::Column::Email)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserEmail,
	#[sea_orm(has_many = "super::user_login::Entity")]
	UserLogin,
	#[sea_orm(
		belongs_to = "super::user_phone_number::Entity",
		from = "(Column::Id, Column::RecoveryPhoneCountryCode, Column::RecoveryPhoneNumber)",
		to = "(super::user_phone_number::Column::UserId, super::user_phone_number::Column::CountryCode, super::user_phone_number::Column::Number)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserPhoneNumber,
	#[sea_orm(has_many = "super::user_social_login::Entity")]
	UserSocialLogin,
	#[sea_orm(has_many = "super::user_unverified_email::Entity")]
	UserUnverifiedEmail,
	#[sea_orm(has_many = "super::user_unverified_phone_number::Entity")]
	UserUnverifiedPhoneNumber,
	#[sea_orm(has_many = "super::workspace::Entity")]
	Workspace,
	#[sea_orm(has_many = "super::workspace_user::Entity")]
	WorkspaceUser,
}

impl Related<super::static_site_upload_history::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::StaticSiteUploadHistory.def()
	}
}

impl Related<super::user_email::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserEmail.def()
	}
}

impl Related<super::user_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserLogin.def()
	}
}

impl Related<super::user_phone_number::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserPhoneNumber.def()
	}
}

impl Related<super::user_social_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserSocialLogin.def()
	}
}

impl Related<super::user_unverified_email::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserUnverifiedEmail.def()
	}
}

impl Related<super::user_unverified_phone_number::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserUnverifiedPhoneNumber.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl Related<super::workspace_user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceUser.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
