//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_phone_number")]
pub struct Model {
	#[sea_orm(unique_key = "user_phone_number_uq_user_id_country_code_number")]
	pub user_id: Uuid,
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "user_phone_number_uq_user_id_country_code_number"
	)]
	pub country_code: String,
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "user_phone_number_uq_user_id_country_code_number"
	)]
	pub number: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::phone_number_country_code::Entity",
		from = "Column::CountryCode",
		to = "super::phone_number_country_code::Column::CountryCode",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	PhoneNumberCountryCode,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::phone_number_country_code::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PhoneNumberCountryCode.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
