//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::SocialLoginProvider;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_social_login")]
pub struct Model {
	#[sea_orm(unique_key = "user_social_login_uq_user_provider")]
	pub user_id: Uuid,
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "user_social_login_uq_user_provider"
	)]
	pub provider: SocialLoginProvider,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub external_id: String,
	pub linked_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
