//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_unverified_email")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		column_type = "Text",
		unique_key = "user_unverified_email_uq_user_id_local_domain_id"
	)]
	pub email: String,
	#[sea_orm(unique_key = "user_unverified_email_uq_user_id_local_domain_id")]
	pub user_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub verification_token_hash: String,
	pub verification_token_expiry: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
