//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::UserLoginType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_api_token")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "user_api_token_token_id_user_id_uk"
	)]
	pub token_id: Uuid,
	#[sea_orm(column_type = "Text", unique_key = "user_api_token_uq_name_user_id")]
	pub name: String,
	#[sea_orm(unique_key = "user_api_token_uq_name_user_id")]
	pub user_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub token_hash: String,
	pub token_nbf: Option<TimeDateTimeWithTimeZone>,
	pub token_exp: Option<TimeDateTimeWithTimeZone>,
	pub allowed_ips: Option<Vec<String>>,
	pub created: TimeDateTimeWithTimeZone,
	pub revoked: Option<TimeDateTimeWithTimeZone>,
	pub login_type: Option<UserLoginType>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::user_api_token_workspace_permission_type::Entity")]
	UserApiTokenWorkspacePermissionType,
	#[sea_orm(has_many = "super::user_api_token_workspace_super_admin::Entity")]
	UserApiTokenWorkspaceSuperAdmin,
	#[sea_orm(
		belongs_to = "super::user_login::Entity",
		from = "(Column::TokenId, Column::UserId, Column::LoginType)",
		to = "(super::user_login::Column::LoginId, super::user_login::Column::UserId, super::user_login::Column::LoginType)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserLogin,
}

impl Related<super::user_api_token_workspace_permission_type::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenWorkspacePermissionType.def()
	}
}

impl Related<super::user_api_token_workspace_super_admin::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenWorkspaceSuperAdmin.def()
	}
}

impl Related<super::user_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserLogin.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
