//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::UserLoginType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_login")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub login_id: Uuid,
	pub original_login_id: Option<Uuid>,
	pub user_id: Uuid,
	#[sea_orm(column_type = "Text")]
	pub refresh_token: String,
	pub token_expiry: TimeDateTimeWithTimeZone,
	pub created: TimeDateTimeWithTimeZone,
	#[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text")]
	pub created_ip: String,
	#[sea_orm(ignore, column_type = "custom(\"geometry\")", select_as = "text")]
	pub created_location: String,
	#[sea_orm(column_type = "Text")]
	pub created_user_agent: String,
	#[sea_orm(column_type = "Text")]
	pub created_country: String,
	#[sea_orm(column_type = "Text")]
	pub created_region: String,
	#[sea_orm(column_type = "Text")]
	pub created_city: String,
	#[sea_orm(column_type = "Text")]
	pub created_timezone: String,
	pub login_type: UserLoginType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user_login::Entity",
		from = "(Column::LoginId, Column::UserId, Column::LoginType)",
		to = "(super::user_login::Column::LoginId, super::user_login::Column::UserId, super::user_login::Column::LoginType)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	UserLogin,
}

impl Related<super::user_login::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserLogin.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
