//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "workspace_uq_id_super_admin_id"
	)]
	pub id: Uuid,
	#[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text", unique)]
	pub name: String,
	#[sea_orm(unique_key = "workspace_uq_id_super_admin_id")]
	pub super_admin_id: Uuid,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::audit_log::Entity")]
	AuditLog,
	#[sea_orm(has_many = "super::container_registry_repository::Entity")]
	ContainerRegistryRepository,
	#[sea_orm(has_many = "super::managed_database::Entity")]
	ManagedDatabase,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "Column::Id",
		to = "super::resource::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(has_many = "super::role::Entity")]
	Role,
	#[sea_orm(has_many = "super::runner::Entity")]
	Runner,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::SuperAdminId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
	#[sea_orm(has_many = "super::user_api_token_workspace_super_admin::Entity")]
	UserApiTokenWorkspaceSuperAdmin,
	#[sea_orm(has_many = "super::workspace_domain::Entity")]
	WorkspaceDomain,
	#[sea_orm(has_many = "super::workspace_user::Entity")]
	WorkspaceUser,
}

impl Related<super::audit_log::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::AuditLog.def()
	}
}

impl Related<super::container_registry_repository::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ContainerRegistryRepository.def()
	}
}

impl Related<super::managed_database::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedDatabase.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::role::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Role.def()
	}
}

impl Related<super::runner::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Runner.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl Related<super::user_api_token_workspace_super_admin::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserApiTokenWorkspaceSuperAdmin.def()
	}
}

impl Related<super::workspace_domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceDomain.def()
	}
}

impl Related<super::workspace_user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::WorkspaceUser.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
