//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::DomainNameserverType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace_domain")]
pub struct Model {
	#[sea_orm(
		primary_key,
		auto_increment = false,
		unique_key = "workspace_domain_uq_id_nameserver_type"
	)]
	pub id: Uuid,
	#[sea_orm(column_type = "Text", unique_key = "workspace_domain_uq_name_tld")]
	pub name: String,
	#[sea_orm(column_type = "Text", unique_key = "workspace_domain_uq_name_tld")]
	pub tld: String,
	pub workspace_id: Uuid,
	#[sea_orm(unique_key = "workspace_domain_uq_id_nameserver_type")]
	pub nameserver_type: DomainNameserverType,
	pub is_verified: bool,
	pub last_verified: Option<TimeDateTimeWithTimeZone>,
	pub deleted: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::domain_tld::Entity",
		from = "Column::Tld",
		to = "super::domain_tld::Column::Tld",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	DomainTld,
	#[sea_orm(has_many = "super::managed_url::Entity")]
	ManagedUrl,
	#[sea_orm(has_many = "super::managed_url_custom_hostname::Entity")]
	ManagedUrlCustomHostname,
	#[sea_orm(has_many = "super::patr_controlled_domain::Entity")]
	PatrControlledDomain,
	#[sea_orm(
		belongs_to = "super::resource::Entity",
		from = "(Column::Id, Column::WorkspaceId, Column::Deleted)",
		to = "(super::resource::Column::Id, super::resource::Column::OwnerId, super::resource::Column::Deleted)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Resource,
	#[sea_orm(has_many = "super::user_controlled_domain::Entity")]
	UserControlledDomain,
	#[sea_orm(
		belongs_to = "super::workspace::Entity",
		from = "Column::WorkspaceId",
		to = "super::workspace::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Workspace,
}

impl Related<super::domain_tld::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DomainTld.def()
	}
}

impl Related<super::managed_url_custom_hostname::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ManagedUrlCustomHostname.def()
	}
}

impl Related<super::patr_controlled_domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PatrControlledDomain.def()
	}
}

impl Related<super::resource::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Resource.def()
	}
}

impl Related<super::user_controlled_domain::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserControlledDomain.def()
	}
}

impl Related<super::workspace::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Workspace.def()
	}
}

impl Related<super::managed_url::Entity> for Entity {
	fn to() -> RelationDef {
		super::managed_url_custom_hostname::Relation::ManagedUrl.def()
	}

	fn via() -> Option<RelationDef> {
		Some(
			super::managed_url_custom_hostname::Relation::WorkspaceDomain
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
