[package]
description = "The self hosted dashboard for Patr"
name = "self-hosted-frontend"

authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { workspace = true, features = [] }
frontend = { workspace = true }
wasm-bindgen = { workspace = true, features = ["default"] }
wasm-logger = { workspace = true, features = [] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
leptos = { workspace = true, features = ["tracing", "hydrate"] }
