[package]
description = "A command line tool for managing your Patr resources"
name        = "cli"

authors.workspace      = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[[bin]]
name = "patr"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap                = { workspace = true, features = ["cargo", "default", "derive", "env", "string"] }
comfy-table         = { workspace = true, features = ["default"] }
common              = { workspace = true, features = [] }
config              = { workspace = true, features = ["default"] }
crossterm           = { workspace = true, features = [] }
dirs                = { workspace = true, features = [] }
docker              = { workspace = true, features = [] }
either              = { workspace = true, features = ["serde"] }
futures             = { workspace = true, features = ["default"] }
headers             = { workspace = true, features = [] }
http                = { workspace = true, features = ["default"] }
if-addrs            = { workspace = true, features = [] }
inquire             = { workspace = true, features = ["console", "date", "default", "editor"] }
macros              = { workspace = true, features = [] }
models              = { workspace = true, features = [] }
open                = { workspace = true, features = [] }
preprocess          = { workspace = true, features = [] }
rand                = { workspace = true, features = ["default"] }
reqwest             = { workspace = true, features = ["default", "json"] }
serde               = { workspace = true, features = ["default", "derive"] }
serde_json          = { workspace = true, features = ["default"] }
serde_path_to_error = { workspace = true, features = [] }
serde_qs            = { workspace = true, features = [] }
serde_yaml2         = { workspace = true, features = [] }
thiserror           = { workspace = true, features = ["default"] }
time                = { workspace = true, features = ["default", "serde-human-readable"] }
tokio               = { workspace = true, features = ["default", "full"] }
tracing             = { workspace = true, features = ["async-await", "default"] }
tracing-log         = { workspace = true, features = ["default"] }
tracing-subscriber  = { workspace = true, features = ["default"] }
typed-builder       = { workspace = true, features = [] }
url                 = { workspace = true, features = ["default"] }
uzers               = { workspace = true, features = ["default"] }

[build-dependencies]
time = { workspace = true, features = [] }
