[package]
name = "docker"

authors.workspace      = true
description.workspace  = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
bollard = { workspace = true, features = ["default"] }
common  = { workspace = true }
futures = { workspace = true, features = ["default"] }
models  = { workspace = true, features = [] }
serde   = { workspace = true, features = ["default", "derive"] }
tokio   = { workspace = true, features = ["full"] }
