use crate::prelude::*;

#[component]
pub fn PasswordSection() -> impl IntoView {
	view! {
		<div class="txt-white fc-fs-fs full-width px-xl py-lg br-sm bg-secondary-light">
			<div class="fr-fs-ct full-width pb-sm ul-light">
				<h2 class="letter-sp-md txt-md">Security</h2>
			</div>

			<form
				class="full-width pt-md gap-md fc-fs-fs"
			>
				<div class="flex full-width px-md">
					<div class="flex-col-2 fr-fs-fs pt-sm txt-sm">
						"Two-Factor"
						<br />
						"Authentication"
					</div>

					<div class="flex-col-10 fc-fs-fs gap-xxs">
						<p class="w-70">
							"Two-Factor Authentication (2FA) adds an extra layer of security to your account by requiring a second form of verification in addition to your password. By enabling 2FA, you'll be prompted to authenticate your login using a unique code generated by an authenticator app, ensuring that only you can access your account."
						</p>

						<Link style_variant=LinkStyleVariant::Contained>
							"ENABLE 2FA"
						</Link>
					</div>
				</div>

				<div class="flex full-width px-md">
					<div class="flex-col-2 fr-fs-fs">
						<label html_for="currentPassword" class="mt-sm txt-sm">
							"Password"
						</label>
					</div>

					<div class="flex-col-10 fc-fs-fs">
						<Input
							id="currentPassword"
							placeholder="Enter Current Password"
							class="full-width"
							variant=SecondaryColorVariant::Medium
						/>
					</div>
				</div>
			</form>

		</div>
	}
}
