services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_ZSH: "false"
        UPGRADE_PACKAGES: "true"

    privileged: true
    init: true
    volumes:
      - ..:/workspace:cached
      # - ./volume/docker:/var/lib/docker

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    user: vscode

    environment:
      - PGHOST=localhost
      - PGUSER=postgres

  postgres:
    image: postgis/postgis:13-master
    restart: unless-stopped
    network_mode: service:app
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7
    restart: unless-stopped
    network_mode: service:app

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    network_mode: service:app
    environment:
      - RABBITMQ_NODENAME=mq
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  docker-registry:
    image: registry:2
    restart: unless-stopped
    network_mode: service:app
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH_TOKEN_SERVICE: "docker-registry"
      REGISTRY_AUTH_TOKEN_ISSUER: "patr"
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/ecdsa.pubkey.crt
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:3000/auth/docker-registry-token
      REGISTRY_HTTP_SECRET: "keyboard cat"
      REGISTRY_NOTIFICATIONS_EVENTS_INCLUDEREFERENCES: "true"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: "- name: notifications-test\n  url: http://localhost:3000/webhook/docker-registry/notification\n  headers:\n    Authorization: [1234567890]\n  timeout: 5s\n  threshold: 8\n  backoff: 10s"
    volumes:
      - ./volume/certs:/certs
