version: '3'

networks:
  vpc:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: sudo /bin/dumb-init /runc.sh
    privileged: true
    user: vscode
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PG_PASSWORD=postgres
    expose:
      - 3000
    volumes:
      - ..:/workspace:cached
      - ./volume/data/cargo:/home/vscode/.cargo-volume
      - ${HOME}/.bash_history:/home/vscode/.bash_history
      - ${HOME}/.netrc:/home/vscode/.netrc
    depends_on:
      - postgres
      - redis
      - opentelemetry
    hostname: backend
    networks:
      vpc:
        aliases:
          - backend
          - frontend

  postgres:
    image: postgis/postgis:13-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
      - PGDATA=/var/lib/postgresql/data
    expose:
      - 5432
    volumes:
      - ./volume/data/postgres:/var/lib/postgresql/data
    hostname: postgres
    networks:
      vpc:
        aliases:
          - postgres

  redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - 6379
    hostname: redis
    networks:
      vpc:
        aliases:
          - redis

  opentelemetry:
    image: jaegertracing/all-in-one:1
    restart: unless-stopped
    expose:
      - 4317
      - 4318
      - 3000:16686
    hostname: opentelemetry
    networks:
      vpc:
        aliases:
          - opentelemetry
