networks:
  vpc:

volumes:
  postgres-data:
  grafana-data:
  tempo-data:
  loki-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    user: vscode
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis
      - tracing
      - logs
      - metrics
      - secrets
    hostname: backend
    networks:
      vpc:
        aliases:
          - backend

  postgres:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
      - PGDATA=/var/lib/postgresql
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql
    hostname: postgres
    networks:
      vpc:
        aliases:
          - postgres

  redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - 6379
    hostname: redis
    networks:
      vpc:
        aliases:
          - redis

  tracing:
    image: grafana/tempo:2.10.1
    command: "-target=scalable-single-binary -config.file=/etc/tempo/tempo.yaml"
    user: root
    restart: unless-stopped
    expose:
      - 3200
      - 9095
      - 4317
      - 4318
    volumes:
      - ../config/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/lib/tempo
    hostname: tracing
    networks:
      vpc:
        aliases:
          - tracing

  logs:
    image: grafana/loki:3.2.0
    restart: unless-stopped
    command: "-config.file=/etc/loki/loki.yaml"
    user: root
    expose:
      - 3100
    volumes:
      - ../config/loki.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/var/lib/loki
    hostname: logs
    networks:
      vpc:
        aliases:
          - logs

  metrics:
    image: grafana/mimir:2.13.0
    restart: unless-stopped
    expose:
      - 8080
    hostname: metrics
    networks:
      vpc:
        aliases:
          - metrics

  secrets:
    image: openbao/openbao:2.5.0
    restart: unless-stopped
    command: server -dev -dev-listen-address=0.0.0.0:8200
    environment:
      - BAO_DEV_ROOT_TOKEN_ID=dev-root-token
    expose:
      - 8200
    hostname: secrets
    networks:
      vpc:
        aliases:
          - secrets

  grafana:
    image: grafana/grafana-enterprise:12.0.2-ubuntu
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ../config/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana
    hostname: grafana
    networks:
      vpc:
        aliases:
          - grafana

  mailcrab:
    image: marlonb/mailcrab:latest
    restart: unless-stopped
    expose:
      - 1080
      - 1025
    hostname: mailcrab
    networks:
      vpc:
        aliases:
          - mailcrab
