[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zlinker-features=-lld"]

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[alias]
serve = "leptos serve"
watch = "leptos watch --hot-reload"
prepare = "sqlx prepare --workspace"
patr = "run -p cli --"
