[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[build]
rustflags = ["--cfg=web_sys_unstable_apis", "-Z", "threads=8"]

[alias]
serve = "leptos serve"
watch = "leptos watch"
prepare = "sqlx prepare --workspace"
patr = "run -p cli --"
