[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "--cfg", "--cfg", "erase_components", "link-arg=-fuse-ld=/usr/local/bin/mold", "web_sys_unstable_apis"]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "--cfg", "--cfg", "erase_components", "link-arg=-fuse-ld=/usr/local/bin/mold", "web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "--cfg", "erase_components", "web_sys_unstable_apis", '--cfg', 'getrandom_backend="wasm_js"']

[alias]
api          = "leptos serve -p dashboard"
docker       = "leptos serve -p docker"
patr         = "run -p cli --"
prepare      = "sqlx prepare --workspace"
watch-api    = "leptos watch -p dashboard --hot-reload"
watch-docker = "leptos watch -p docker --hot-reload"
