[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']


[alias]
api = "leptos serve -p dashboard"
docker = "leptos serve -p docker"
patr = "run -p cli --"
prepare = "sqlx prepare --workspace"
watch-api = "leptos watch -p dashboard"
watch-docker = "leptos watch -p docker"
