server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

compactor:
  compaction:
    block_retention: 72h # Retain blocks for 3 days

storage:
  trace:
    backend: "local"
    local:
      path: /var/lib/tempo/traces
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: tracing:9095
