apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-domain-wildcard-patr-cloud
spec:
  dnsNames:
    - "example.com"
    - "*.example.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  secretName: tls-domain-wildcard-patr-cloud
