auth_enabled: true

target: all

server:
  http_listen_address: "0.0.0.0"
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki
  replication_factor: 1 # Increase when adding replicas

# memberlist:
#   join_members:
#     - logging:7946 # DNS-based peer discovery in deployment

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1 # Increase when adding replicas
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s

storage_config:
  object_prefix: loki
  aws:
    endpoint: CHANGE_ME # Override via -s3.endpoint
    region: CHANGE_ME # Override via -s3.region
    s3forcepathstyle: true
    bucketnames: CHANGE_ME # Override via -s3.buckets
    access_key_id: CHANGE_ME # Override via -s3.access-key-id
    secret_access_key: CHANGE_ME # Override via -s3.secret-access-key

compactor:
  working_directory: /var/lib/loki/compactor
  retention_enabled: true
  delete_request_store: s3

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 720h # 30 days
  allow_structured_metadata: true
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  volume_enabled: true

runtime_config:
  file: /etc/loki/loki-overrides.yaml
  period: 10s
