overrides:
  patr:
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    max_streams_per_user: 10000
    max_global_streams_per_user: 10000
    max_chunks_per_query: 2000000
    max_query_series: 500
    max_query_parallelism: 32
    max_query_length: 720h # 30 days
    max_entries_limit_per_query: 5000
    retention_period: 720h # 30 days
    per_stream_rate_limit: 3MB
    per_stream_rate_limit_burst: 15MB
