kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: base-kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
    # install reflector to mirror secrets in all namespaces
  - https://github.com/emberstack/kubernetes-reflector/releases/download/v6.1.47/reflector.yaml
  
    # create cloudflare api token as secret in all namespaces
  - ./cloudflare-api-token.yml
  
    # install cert manager resources for certificate handling
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

    # configure cert manager to use cloudflare
  - ./certificate-issuer.yml

    # create wildcard domains certificate for ingress
  - ./wildcard-cluster-certificate.yml

    # install nginx resources for ingress handling
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml

patchesJson6902:
  # patch for using default wildcard certificate for all ingress routes
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: 
        --default-ssl-certificate=default/tls-domain-wildcard-patr-cloud
