[package]
description = "The cloudflare worker script that proxies requests to the right cluster"
name        = "ingress"

authors.workspace      = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
models = { workspace = true, features = [] }
url    = { workspace = true, features = ["default"] }
worker = { workspace = true, features = [] }
