[package]
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
name                   = "isolated"
rust-version.workspace = true
version.workspace      = true

[dependencies]
axum        = { workspace = true, features = ["default", "macros", "tracing"] }
frontend    = { workspace = true, features = [] }
leptos      = { workspace = true, features = ["ssr"] }
leptos_axum = { workspace = true, features = ["default"] }
reqwest     = { workspace = true, features = ["default", "json", "multipart", "blocking"] }
tokio       = { workspace = true, features = ["default", "full"] }
tower-http  = { workspace = true, features = ["fs"] }

[lints]
workspace = true
