//! Migrations for version 0.18.0

mod m001_initial_baseline;
mod m002_per_url_custom_hostnames;
mod m003_github_sso;
mod m004_sign_up_attempts;
mod m005_allow_null_manifest_config_and_platform;
mod m006_normalize_registry_schema;
mod m007_unify_domains;
mod m008_simplify_workspace_name_index;
mod m009_scope_roles_to_workspace;
mod m010_workspace_user_invites;
mod m011_email_as_identity;
mod m012_remove_static_sites_and_databases;
mod m013_drop_static_site_url_type;
mod m014_rename_owner_id_to_workspace_id;
mod m015_actor_client_registry;
mod m016_audit_log_actor_client_id;
mod m017_role_permission_flat_list;
mod m018_workspace_actor;
mod m019_role_binding;
mod m020_backfill_role_bindings;
mod m021_role_binding_cutover;
mod m022_token_ceiling_evaluation;
mod m023_drop_legacy_permission_tables;
mod m024_add_service_accounts;
mod m025_runner_version;
