[package]
name = "macros"

authors.workspace      = true
description.workspace  = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = { workspace = true }
proc-macro2  = { workspace = true, features = ["default"] }
quote        = { workspace = true, features = ["default"] }
regex        = { workspace = true, features = ["default"] }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true, features = ["default"] }
syn          = { workspace = true, features = ["default", "full"] }
mrml         = { workspace = true, features = ["parse", "render"] }

[dev-dependencies]
axum       = { workspace = true }
axum-extra = { workspace = true }
headers    = { workspace = true }
http       = { workspace = true }
models     = { workspace = true }
preprocess = { workspace = true }
tracing    = { workspace = true }
