use convert_case::{Case, Casing};
use proc_macro::TokenStream;
use quote::format_ident;
use syn::{Data, DataStruct, DeriveInput, Error, Member, parse_macro_input, spanned::Spanned};

/// Provides a derive macro for the `HasHeaders` trait.
pub fn parse(input: TokenStream) -> TokenStream {
	let DeriveInput {
		data, ident, vis, ..
	} = parse_macro_input!(input as DeriveInput);

	let DataStruct { fields, .. } = match data {
		Data::Struct(data) => data,
		Data::Enum(data) => {
			return Error::new(data.enum_token.span(), "expected struct")
				.into_compile_error()
				.into();
		}
		Data::Union(data) => {
			return Error::new(data.union_token.span(), "expected struct")
				.into_compile_error()
				.into();
		}
	};

	let pascal_cased_fields_list = fields
		.members()
		.map(|field| {
			let Member::Named(name) = field else {
				return Err(Error::new(field.span(), "expected named field").into_compile_error());
			};
			let field = format_ident!(
				"{}",
				name.to_string()
					.as_str()
					.trim_start_matches("r#")
					.to_case(Case::Pascal)
			);

			Ok(quote::quote! {
				#[doc = "This field represents the `"]
				#[doc = "#field"]
				#[doc = "` field of the `"]
				#[doc = "#ident"]
				#[doc = "` struct that can be used to list resources."]
				#field
			})
		})
		.collect::<Result<Vec<_>, _>>();

	let pascal_cased_fields_list = match pascal_cased_fields_list {
		Ok(fields) => fields,
		Err(err) => return err.into(),
	};

	let fields_name = format_ident!("{ident}FieldList");

	quote::quote! {
		#[doc = "This enum represents the fields of the `"]
		#[doc = "#ident"]
		#[doc = "` struct that can be used to list resources."]
		#[doc = "It is used to specify which fields should be included in the response."]
		#[doc = "It is automatically generated by the `ListableResource` derive macro."]
		#[doc = "You should not need to use this enum directly, but it is available for reference."]
		#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ::serde::Serialize, ::serde::Deserialize, PartialOrd, Ord)]
		#[serde(rename_all = "camelCase")]
		#vis enum #fields_name {
			#(#pascal_cased_fields_list),*
		}

		impl models::utils::ListableResource for #ident {
			type FieldList = #fields_name;
			type SearchStruct = ();
		}
	}
	.into()
}
