use std::collections::BTreeMap;

use proc_macro::TokenStream;
use syn::{Error, Ident, ItemEnum, Type, parse::Parse};

/// Struct that represents the input to the `RecursiveEnumIter` derive macro.
pub struct RecursiveEnumIter {
	/// The name of the enum.
	name: Ident,
	/// A map from variant names to the types of the fields of the variant.
	variants: BTreeMap<Ident, Vec<Type>>,
}

impl Parse for RecursiveEnumIter {
	fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
		let variants = input.parse::<ItemEnum>()?;
		let name = variants.ident;
		let variants = variants
			.variants
			.into_iter()
			.map(|variant| {
				let fields = match variant.fields {
					syn::Fields::Unit => vec![],
					syn::Fields::Named(fields) => {
						fields.named.into_iter().map(|field| field.ty).collect()
					}
					syn::Fields::Unnamed(fields) => {
						fields.unnamed.into_iter().map(|field| field.ty).collect()
					}
				};
				(variant.ident, fields)
			})
			.collect();
		Ok(Self { name, variants })
	}
}

/// Derive macro that generates an `iter` method for an enum that returns an
/// iterator over all possible variants of the enum. This iterator is recursive,
/// meaning that it will also iterate over all possible variants of any enum
/// fields.
pub fn parse(input: TokenStream) -> TokenStream {
	let RecursiveEnumIter { variants, name } = syn::parse_macro_input!(input as RecursiveEnumIter);
	let iter = variants
		.into_iter()
		.enumerate()
		.map(|(index, (variant, types))| {
			let mut types = types.into_iter();
			let r#type = types.next();

			let Some(r#type) = r#type else {
				return Ok(if index == 0 {
					quote::quote! {
						::std::iter::once(Self::#variant)
					}
				} else {
					quote::quote! {
						.chain(::std::iter::once(Self::#variant))
					}
				});
			};

			let None = types.next() else {
				return Err(Error::new(
					variant.span(),
					"RecursiveEnumIter only supports variants with zero or one field",
				));
			};

			Ok(if index == 0 {
				quote::quote! {
					#r#type::iter().map(Self::#variant)
				}
			} else {
				quote::quote! {
					.chain(#r#type::iter().map(Self::#variant))
				}
			})
		})
		.collect::<Result<Vec<_>, _>>();

	let iter = match iter {
		Ok(iter) => iter,
		Err(err) => return err.to_compile_error().into(),
	};

	quote::quote! {
		impl #name {
			/// Returns an iterator over all possible variants of this enum. This iterator is
			/// recursive, meaning that it will also iterate over all possible variants of any
			/// enum fields. This is autogenerated by the `RecursiveEnumIter` derive macro.
			fn iter() -> impl ::std::iter::Iterator<Item = Self> {
				#(#iter)*
			}
		}
	}
	.into()
}
