[package]
name = "controller"
edition.workspace = true
version.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
k8s-openapi = { version = "0.19", features = ["v1_24"] }
kube = { version = "0.85", features = ["ws"] }
tokio = { workspace = true, features = ["tracing"] }
