[package]
name = "controller"
edition.workspace = true
version.workspace = true
description.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }
kube = { version = "0.84.0", features = ["ws"] }
tokio = { workspace = true, features = ["tracing"] }
