use std::io;

use thiserror::Error;
use tracing::subscriber::SetGlobalDefaultError;

use crate::prelude::*;

/// A list of all the possible errors that can be generated by the runner
#[derive(Debug, Error)]
pub enum RunnerError {
	/// An error that is generated by the local SQLite database
	#[error("database error: {0}")]
	DatabaseError(#[from] sqlx::Error),
	/// Error while communicating with the upstream Patr API
	#[error("server error from upstream API: {0}")]
	UpstreamServerError(ErrorType),
	/// Error parsing the configuration file for the runner
	#[error("error parsing configuration: {0}")]
	ConfigurationError(#[from] config::ConfigError),
	/// Error while setting up the Axum server for the runner
	#[error("error initializing the server: {0}")]
	ServerSetupError(#[from] io::Error),
	/// Error while setting the global default subscriber for tracing
	#[error("error setting the global default subscriber: {0}")]
	TracingSubscriberError(#[from] SetGlobalDefaultError),
}

impl From<ErrorType> for RunnerError {
	fn from(error: ErrorType) -> Self {
		Self::UpstreamServerError(error)
	}
}
