[package]
name = "api"

authors.workspace      = true
autotests              = false
description.workspace  = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]
cloud   = ["models/cloud"]
default = ["cloud"]

[dependencies]
apalis                         = { workspace = true, features = ["tracing"] }
apalis-cron                    = { workspace = true, features = ["cron", "serde"] }
apalis-postgres                = { workspace = true, features = ["migrate", "tokio", "time"] }
argon2                         = { workspace = true, features = ["default"] }
askama                         = { workspace = true, features = ["derive", "config", "std", "urlencode"] }
aws-config                     = { workspace = true, features = [] }
aws-credential-types           = { workspace = true, features = ["hardcoded-credentials"] }
aws-sdk-s3                     = { workspace = true, features = ["rt-tokio", "behavior-version-latest", "default-https-client", "rustls", "http-1x"] }
axum                           = { workspace = true, features = ["default", "macros", "tracing"] }
axum-extra                     = { workspace = true, features = ["default", "typed-routing"] }
axum-typed-websockets          = { workspace = true, features = ["default"] }
base32                         = { workspace = true, features = [] }
base64                         = { workspace = true, features = ["default"] }
clap                           = { workspace = true, features = ["std", "derive"] }
cloudflare                     = { workspace = true, features = ["rustls-tls"] }
config                         = { workspace = true, features = ["json", "convert-case"] }
console-subscriber             = { workspace = true, features = ["default"] }
cron                           = { workspace = true, features = [] }
derive_more                    = { workspace = true, features = ["from"] }
futures                        = { workspace = true, features = ["default"] }
headers                        = { workspace = true, features = [] }
hex                            = { workspace = true, features = [] }
hickory-resolver               = { workspace = true, features = ["tokio"] }
http                           = { workspace = true, features = ["default"] }
http-body                      = { workspace = true, features = [] }
inventory                      = { workspace = true, features = [] }
ipinfo                         = { workspace = true, features = [] }
jsonwebtoken                   = { workspace = true, features = ["default", "aws_lc_rs"] }
lettre                         = { workspace = true, features = ["tokio1-rustls-tls", "smtp-transport", "builder", "tokio1"] }
macros                         = { workspace = true, features = [] }
mime_guess                     = { workspace = true, features = ["default"] }
models                         = { workspace = true, features = ["axum"] }
oci-spec                       = { workspace = true, features = ["distribution", "image"] }
opentelemetry                  = { workspace = true, features = ["default"] }
opentelemetry-appender-tracing = { workspace = true, features = ["default"] }
opentelemetry-otlp             = { workspace = true, features = ["default", "tonic", "tokio", "reqwest-rustls-webpki-roots", "grpc-tonic", "http-json", "metrics"] }
opentelemetry-proto            = { workspace = true, features = ["gen-tonic-messages", "with-serde", "logs", "metrics"] }
opentelemetry_sdk              = { workspace = true, features = ["default", "rt-tokio"] }
pin-project                    = { workspace = true, features = [] }
preprocess                     = { workspace = true, features = [] }
prost                          = { workspace = true, features = [] }
prost-types                    = { workspace = true, features = [] }
psl                            = { workspace = true, features = ["default"] }
rand                           = { workspace = true, features = ["default"] }
regex                          = { workspace = true, features = ["default"] }
reqwest                        = { workspace = true, features = ["default", "json", "multipart", "blocking", "stream", "query", "form"] }
rust-embed                     = { workspace = true, features = ["interpolate-folder-path", "mime-guess"] }
rustis                         = { workspace = true, features = ["default", "pool", "tokio-rustls"] }
semver                         = { workspace = true, features = ["default"] }
serde                          = { workspace = true, features = ["default", "derive"] }
serde_json                     = { workspace = true, features = ["default"] }
serde_qs                       = { workspace = true, features = [] }
sha2                           = { workspace = true, features = ["default"] }
snap                           = { workspace = true, features = [] }
sqlx                           = { workspace = true, features = ["ipnetwork", "macros", "postgres", "runtime-tokio", "time", "tls-rustls", "uuid", "json"] }
sync_wrapper                   = { workspace = true, features = [] }
time                           = { workspace = true, features = ["default", "serde-human-readable"] }
tokio                          = { workspace = true, features = ["default", "full", "tracing"] }
tokio-tungstenite              = { workspace = true, features = ["default"] }
tokio-util                     = { workspace = true, features = ["io"] }
totp-rs                        = { workspace = true, features = ["default", "gen_secret", "otpauth", "qr"] }
tower                          = { workspace = true, features = ["full"] }
tower-http                     = { workspace = true, features = ["fs"] }
tracing                        = { workspace = true, features = ["async-await", "default"] }
tracing-opentelemetry          = { workspace = true, features = ["default"] }
tracing-subscriber             = { workspace = true, features = ["default"] }
typed-builder                  = { workspace = true, features = [] }
woothee                        = { workspace = true, features = ["default"] }

[dev-dependencies]
anyhow    = { workspace = true, features = ["default"] }
axum-test = { workspace = true, features = ["default"] }
flate2    = { workspace = true, features = ["rust_backend"] }
ipnetwork = { workspace = true, features = ["default"] }
tar       = { workspace = true, features = [] }
wiremock  = { workspace = true, features = [] }

[[test]]
name = "integration-tests"
path = "tests/mod.rs"
