[package]
name = "models"

authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
server = [
	"axum/http1",
	"axum/http2",
	"axum/matched-path",
	"axum/original-uri",
	"axum/tokio",
	"axum/tower-log",
	"axum/ws",
	"axum/tracing",
	"axum-typed-websockets",
	"reqwest/default",
	"uuid/js",
]
default = ["server"]

[dependencies]
anyhow = "1"
axum = { version = "0.6", features = [
	"form",
	"json",
	"query",
], default-features = false }
axum-extra = { version = "0.7", features = ["typed-routing"] }
axum-typed-websockets = { version = "0.5", optional = true }
hex = "0.4"
log = "0.4"
macros = { workspace = true }
reqwest = { version = "0.11", features = [
	"rustls-tls",
	"json",
], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_test = "1"
tower = { version = "0.4", features = ["tracing"] }
typed-headers = "0.2"
uuid = { version = "1", features = ["v4"] }
