[package]
name = "models"

authors.workspace      = true
description.workspace  = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]
axum    = ["dep:axum-typed-websockets"]
default = []

[dependencies]
axum                  = { workspace = true, features = ["json"] }
axum-extra            = { workspace = true, features = ["typed-routing"] }
axum-typed-websockets = { workspace = true, features = ["default"], optional = true }
base64                = { workspace = true, features = ["default"] }
either                = { workspace = true, features = ["serde"] }
headers               = { workspace = true, features = [] }
hex                   = { workspace = true, features = ["default"] }
http                  = { workspace = true, features = ["default"] }
ipnetwork             = { workspace = true, features = ["default"] }
macros                = { workspace = true, features = [] }
preprocess            = { workspace = true, features = [] }
schemars              = { workspace = true, features = ["default", "uuid1"] }
serde                 = { workspace = true, features = ["default", "derive"] }
serde_json            = { workspace = true, features = ["default"] }
serde_test            = { workspace = true, features = [] }
sqlx                  = { workspace = true, features = ["macros", "postgres", "sqlite", "uuid"] }
strum                 = { workspace = true, features = ["default", "derive"] }
thiserror             = { workspace = true, features = [] }
time                  = { workspace = true, features = ["default", "serde-human-readable"] }
tower                 = { workspace = true }
tracing               = { workspace = true, features = ["attributes"] }
typed-builder         = { workspace = true, features = [] }
uuid                  = { workspace = true, features = ["default", "v1", "v4"] }
