[package]
description = "The frontend dashboard for Patr"
name        = "frontend"

authors.workspace      = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
dioxus     = { workspace = true, features = ["default", "router", "web"] }
dioxus-sdk = { workspace = true, features = ["storage"] }
macros     = { workspace = true }
models     = { workspace = true }
semver     = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
