[package]
description = "The frontend dashboard for Patr"
name        = "frontend"

authors.workspace      = true
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]
# default = ["dioxus/fullstack", "dioxus/liveview", "dioxus/server", "dioxus/ssr"]

[dependencies]
console_error_panic_hook = { workspace = true }
dioxus                   = { workspace = true, features = ["default", "router", "web", "document"] }
dioxus-sdk               = { workspace = true, features = ["storage", "timing"] }
http                     = { workspace = true, features = ["default"] }
log                      = { workspace = true, features = ["std"] }
macros                   = { workspace = true }
models                   = { workspace = true }
reqwest                  = { workspace = true, features = ["default", "json"] }
semver                   = { workspace = true }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true, features = ["default"] }
serde_urlencoded         = { workspace = true }
strum                    = { workspace = true }
tracing-wasm             = { workspace = true }
url                      = { workspace = true, features = ["serde"] }
wasm-logger              = { workspace = true }
